/**
 * @fileoverview Root Layout Component
 * @author Flore (with guidance from Marco)
 * 
 * Hey Flore! This is the root layout component that wraps all pages.
 * As I explained, we use this to:
 * 1. Set up fonts
 * 2. Configure theme provider
 * 3. Add global styles
 * 
 * Remember how we discussed that Next.js uses this layout for consistent styling!
 */

import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/components/ui/theme-provider";
import { Roboto } from 'next/font/google';

// Flore, these font configurations are important for consistent typography
// We're using Roboto as our main font and GeistMono for code sections
const roboto = Roboto({
  subsets: ['latin'],
  weight: ['100', '300', '400', '500', '700', '900'],
  variable: '--font-roboto',
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${geistMono.variable} font-roboto antialiased selection:bg-primary/10 selection:text-primary`}
      >
        {/* 
          Flore, remember how we set up dark mode as default?
          This ThemeProvider helps us manage light/dark themes easily!
        */}
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
        {children}</ThemeProvider>
      </body>
    </html>
  );
}
